### ISSUE TITLE
Preemptive merge

### ISSUE THREAD

**Issue by erinann** [ices-publications/AcMeta#8]
Hey @TimRyan99 ,

Would you please check the version of AcMeta currently in the repo? I approved your PR without realizing that you had asked @gavinmacaulay to review it. So, I reverted the merge and now I think the document is back to the state it was before you submitted your PR on July 1, but your PR is gone. Sorry about that. I can probably revert the revert (but that's getting messy). Please resubmit your PR (commits: b75c2356c639469f928aff9e5e748f3959b67f93, 1264265a8bf3b696247aaba963adf8a7e0959027, and 2cf08bcf97473b43f60cd0d83e0dd0c9458df47c) and assign Gavin as the reviewer. I promise I won't touch it.

again, sorry.

**Comment by gavinmacaulay** [comment]
Also, my apologies for not seeing the review flag - I had looked at the PR and it was fine by me...
